---
- name: Add required dependencies.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present
    update_cache: true

- name: Add td-agent apt key.
  apt_key:
    url: "{{ fluentd_repo_url }}/GPG-KEY-td-agent"
    state: present

- name: Add td-agent repository.
  apt_repository:
    repo: >-
      deb
      {{ fluentd_repo_url }}/{{ fluentd_version }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/
      {{ ansible_distribution_release | lower }} contrib
    state: present
    update_cache: true
